name: 'review-manager'
description: 'Manage code reviews for your PRs'
inputs:
  min_approving_reviews_total:
    description: 'Min number of total approving reviews for success'
    required: false
    default: 2
  min_approving_reviews_per_area:
    description: 'Min number of approving reviews for each area label'
    required: false
    default: 1
  area_ownership_file:
    description: 'Repository file which includes the owners for each area label'
    required: true
    default: '.github/AREA-OWNERS'
runs:
  using: 'node12'
  main: 'dist/index.js'
